main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Object for logging events.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <description>This field captures the value of the error code from the Integration in case of a failure.</description>
    <label>Error Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Log level</description>
    <label>Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Log message</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>The response while making a callout.</description>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/classes/CalloutLoggerImplTest.cls
/**
 * @author Rohit Alladi
 * @date  11/16/2017.
 * @group-content ../ApexDocContent/TestClasses.html
 * @description This Test class is used for default implementation, CalloutLoggerImpl
 **/
@IsTest
private class CalloutLoggerImplTest {

    /**
     * Method Tested: debug
     * | Scenario: Called
     * | Expected Result: Record created in Log__c with Debug level
     **/
    static testMethod void debug_Called_RecordCreatedAtCorrectLoggingLevel() {

        Logger logger = LoggerFactory.getCalloutLogger('MyLogName');

        Test.startTest();
        logger.debug('Test error message');
        Test.stopTest();

        Log__c[] logs = [select Id, Name, Level__c, Message__c,Response__c from Log__c limit 1];

        System.assertEquals(1, logs.size(), 'Expected creation of one log record.');
        System.assertEquals(String.valueOf(LogLevel.DEBUG), logs[0].Level__c, 'Log level should be DEBUG.');
    }
    
    /**
     * Method Tested: debug
     * | Scenario: Callout Logger implementation
     * | Expected Result: Record created in Log__c with callout params.
     **/
    static testMethod void debug_CalloutLogger_RecordCreatedAtCorrectLoggingLevel() {

        LogEventData led = new LogEventData();
        led.calloutEndpoint = 'Https://www.google.com';
        led.errorCode = 'Err-1234';
        led.httpMethod = 'POST';
        led.request = 'Request';
        led.response = 'Response';
        led.userId = String.ValueOf(UserInfo.getUserId());
        led.level = LogLevel.INFO;

        Logger logger = LoggerFactory.getCalloutLogger('MyLogName');
        Test.startTest();
        logger.log(led);
        Test.stopTest();

        Log__c[] logs = [select Id, Name, Level__c, Message__c,Response__c,Error_Code__c from Log__c limit 1];

        System.assertEquals(1, logs.size(), 'Expected creation of one log record.');
        System.assertEquals('Err-1234', logs[0].Error_Code__c, 'Error should be Err-1234.');
    }
}