main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Object for logging events.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Callout_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Callout_Endpoint__c</fullName>
    <description>This field denotes the value of a triggered transaction's endpoint.</description>
    <label>Callout Endpoint</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <description>This field captures the value of the error code from the Integration in case of a failure.</description>
    <label>Error Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Http_Method__c.field-meta.xml
<CustomField>
    <fullName>Http_Method__c</fullName>
    <description>This field stores the callout Http Method for the integration.</description>
    <label>Http Method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Log level</description>
    <label>Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Log message</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>The request when making a callout.</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>The response while making a callout.</description>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>Id of the current user.</description>
    <label>User ID</label>
    <type>TextArea</type>
</CustomField>

main/default/classes/CalloutLogWriter.cls
/**
 * @author Rohit Alladi
 * @date Jun 2018
 * @group-content ../ApexDocContent/Classes.html
 * @description Writer for the callout logger
 **/
public with sharing class CalloutLogWriter implements LogWriter {

    public void writeToCustomObject(
            String customObjectName, Map<LogFields, String> logFieldMap, LogEventData data) {

        if (customObjectName == 'Log__c') {
            Log__c log = new Log__c(
            Level__c=data.level.name(),
            Message__c=data.message,
            Callout_Endpoint__c=data.calloutEndpoint,
            Error_Code__c=data.errorCode,
            Http_Method__c=data.httpMethod, Request__c=data.request,
            Response__c=data.response, User_Id__c=data.userId);
            insert log;
        }
    }
}